---
- name: Add multiple VINIC while creating a partition
  hosts: hmcs
  collections:
      - ibm.power_hmc
  connection: local
  vars:
    curr_hmc_auth:
      username: hscroot
      password: abc123

  tasks:
  - name: Create logical partition with mem, shared proc, storage, network config and npiv
    powervm_lpar_instance:
      hmc_host: '{{ inventory_hostname }}'
      hmc_auth: "{{ curr_hmc_auth }}"
      system_name: bX76a
      vm_name: testAnsi1
      proc: 2
      proc_unit: 2
      mem: 2048
      os_type: aix_linux
      max_virtual_slots: 50
      vnic_config:
        - vnic_adapter_id: 9
          backing_devices:
          - location_code: C5-C1-T3
            capacity: 2
            hosting_partition: b76-vios1
      state: present
    register: testout

  - name: Stdout the created logical partition
    debug:
        msg: '{{ testout }}'
