---
- name: When vnic id not passed but backing device passed, pick next available backing device
  hosts: hmcs
  collections:
      - ibm.power_hmc
  connection: local
  vars:
    curr_hmc_auth:
      username: hscroot
      password: abc123

  tasks:
  - name: Create logical partition with mem, shared proc, storage, network config and npiv
    powervm_lpar_instance:
      hmc_host: '{{ inventory_hostname }}'
      hmc_auth: "{{ curr_hmc_auth }}"
      system_name: zepfp06
      vm_name: AnsibleTest1
      os_type: aix_linux
      max_virtual_slots: 50
      vnic_config:
        - vnic_adapter_id: 9
#          backing_devices:
#          - location_code: P0-C2-C0-T0
#            capacity: 2000
#            hosting_partition: d52-vios2
      state: present
    register: testout

  - name: Stdout the created logical partition
    debug:
        msg: '{{ testout }}'
