---
- name: When vnic id passed and backing device not passed pick any of the backing device whose link status is up but if capacity is less than 2.0 then look for the next backing device with link status up
  hosts: hmcs
  collections:
      - ibm.power_hmc
  connection: local
  vars:
    curr_hmc_auth:
      username: hscroot
      password: abc123

  tasks:
  - name: Create logical partition with mem, shared proc, storage, network config and npiv
    powervm_lpar_instance:
      hmc_host: '{{ inventory_hostname }}'
      hmc_auth: "{{ curr_hmc_auth }}"
      system_name: zepp31fp
      vm_name: testAnsi6
      proc: 2
      proc_unit: 2
      mem: 2048
      os_type: aix_linux
      max_virtual_slots: 50
      volume_config:
        - volume_size: 1
      virt_network_config:
        - network_name: VirtualNetwork_503Vswtch0
          slot_number: 49
      npiv_config:
        - vios_name: zepp31-vios1
          fc_port: fcs0
      vnic_config:
        - vnic_adapter_id: 9
      state: present
    register: testout

  - name: Stdout the created logical partition
    debug:
        msg: '{{ testout }}'
