---
- name: Add multiple VINIC while creating a partition
  hosts: hmcs
  collections:
      - ibm.power_hmc
  connection: local
  vars:
    curr_hmc_auth:
      username: hscroot
      password: abc123

  tasks:
  - name: Create logical partition with mem, shared proc, storage, network config and npiv
    powervm_lpar_instance:
      hmc_host: '{{ inventory_hostname }}'
      hmc_auth: "{{ curr_hmc_auth }}"
      vm_name: Ansi4
      system_name: d52a
      os_type: ibmi
      max_virtual_slots: 50
      vnic_config:
        - vnic_adapter_id: 9
      vm_id: 96
      state: present
    register: testout

  - name: Stdout the created logical partition
    debug:
        msg: '{{ testout }}'
