---
- name: Add multiple VINIC while creating a partition
  hosts: hmcs
  collections:
      - ibm.power_hmc
  connection: local
  vars:
    curr_hmc_auth:
      username: hscroot
      password: abc123

  tasks:
  - name: Create logical partition with mem, shared proc, storage, network config and npiv
    powervm_lpar_instance:
      hmc_host: '{{ inventory_hostname }}'
      hmc_auth: "{{ curr_hmc_auth }}"
      system_name: bX76a
      os_type: aix
      vm_name: test11
      vnic_config:
        - vnic_adapter_id: 9
          backing_devices:
          - location_code: P1-C5-C1-T1
            capacity: 2
            hosting_partition: b76-vios1
        - vnic_adapter_id: 11
          backing_devices:
          - location_code: P1-C5-C1-T4
            capacity: 50
#            hosting_partition: zepp31-vios1
        - vnic_adapter_id: 12
#          backing_devices:
#          - location_code: P1-C8-T2
#            capacity: 24
#            hosting_partition: zepp31-vios1
      state: present
    register: testout

  - name: Stdout the created logical partition
    debug:
        msg: '{{ testout }}'
