---
- name: Verify that play creates local user successfully
  hosts: hmcs
  collections:
      - ibm.power_hmc
  connection: local

  tasks:
  - name: Create hmc user
    hmc_user:
      state: present
      hmc_host: "{{ inventory_hostname }}"
      name: Ansible2
      hmc_auth:
        username: hscroot
        password: abc123
      attributes:
        resourcerole: AllSystemResources
        authentication_type: local
        passwd: abcd1234
        taskrole: hmcsuperadmin
    register: result

  - name: Output Users
    debug:
      msg: "{{ result }}"

