---
- name: Verify that play throws error when missing authentication_type reports error
  hosts: hmcs
  collections:
      - ibm.power_hmc
  connection: local

  tasks:
  - name: Create hmc user
    hmc_user:
      state: updated
      hmc_host: "{{ inventory_hostname }}"
      name: hmcldap6
      hmc_auth:
        username: hscroot
        password: abc123
      attributes:
        authentication_type: local
        passwd: abcd123456
        taskrole: hmcservicerep
        remote_webui_access: 1
        remote_ssh_access: 0
        min_pwage: 9
        session_timeout: 10
        verify_timeout: 30
        idle_timeout: 100
        inactivity_expiration: 3
#        passwd_authentication: 
    register: result

  - name: Output Users
    debug:
      msg: "{{ result }}"

