---
- name: Verify that play throws error when remote_user_name is mentioned in Ldap user creation
  hosts: hmcs
  collections:
      - ibm.power_hmc
  connection: local

  tasks:
  - name: Create hmc user
    hmc_user:
      state: present
      hmc_host: "{{ inventory_hostname }}"
      name: hmcldap3
      hmc_auth:
        username: hscroot
        password: abc123
      attributes:
        resourcerole: Test
        authentication_type: ldap
        taskrole: hmcviewer
    register: result

  - name: Output Users
    debug:
      msg: "{{ result }}"

